---

- name: copy load balancer config
  template:
    src: site.j2
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ nginx_site_name }}"
  notify:
    - reload nginx

- name: disable default virtual host
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - reload nginx

- name: force run handler
  meta: flush_handlers
