---

- name: copy virtual hosts configs
  template:
    src: site.j2
    dest: "{{ nginx_sites_available_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ nginx_site_name }}"

- name: create virtual hosts folders
  file:
    path: "/var/www/{{ item }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  with_items:
    - "{{ nginx_site_name }}"

- name: create index files for virtual hosts
  template:
    src: index.html.j2
    dest: /var/www/{{ item }}/index.html
  with_items:
    - "{{ nginx_site_name }}"

- name: create virtual hosts symlinks
  file:
    src: "{{ nginx_sites_available_path }}/{{ item }}"
    dest: "{{ nginx_sites_enabled_path }}/{{ item }}"
    owner: root
    group: root
    state: link
  with_items:
    - "{{ nginx_site_name }}"
  notify:
    - reload nginx

- name: disable default virtual host
  file:
    path: "{{ nginx_sites_enabled_path }}/default"
    state: absent
  notify:
    - reload nginx

- name: force run handler
  meta: flush_handlers
